### ISSUE TITLE
What the hell is wrong with you?

### ISSUE THREAD

**Issue by cal3432** [NextWork123/AllinOneTweaks#2]
You steal my code, mark it as your own, and completely ignore the license on my code.

Expect a DMCA soon unless you take this down or credit DiscordTweaks, me and use the license stated on my code.

**Comment by cal3432** [comment]
You know what, fuck it, you pissed me off. Expect a DMCA TODAY. FULL STOP.

**Comment by NextWork123** [comment]
Hi Sir,
The license you put on your project say "You are free to: Share — copy and redistribute the material in any medium or format. Adapt — remix, transform, and build upon the material The licensor cannot revoke these freedoms as long as you follow the license terms." I think the change of the name isn't violating the dcma but my project is based on your work. If you want i can put credits on the readme and where you want.

Best Regards
NextWorks
